# Generated by Django 6.1.1 on 2026-09-26 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0014_rename_facility_bookings_facilitybookings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allocation_type', models.CharField(choices=[('fixed_equal', 'Fixed Equal'), ('by_person_count', 'By Person Count'), ('by_area_sqm', 'By Area Sqm'), ('custom', 'Custom')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_target', models.CharField(choices=[('any', 'Any'), ('tenant_only', 'Tenant Only'), ('owner_only', 'Owner Only')], max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amount', models.FloatField()),
                ('expense_date', models.DateTimeField()),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseAllocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_basis', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.unit')),
                ('expenses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expenses')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=30)),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expenses')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.invoices')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('online_gateway', 'Online Gateway'), ('pos', 'Pos'), ('cash', 'Cash'), ('card_to_card', 'Card To Card')], max_length=20)),
                ('receipt_attachment', models.URLField()),
                ('tracking_code', models.CharField(max_length=100)),
                ('reference_id', models.CharField(max_length=100)),
                ('paid_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending_approval', max_length=20)),
                ('invoice_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.invoices')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.unit')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
