# Generated by Django 6.1.1 on 2026-09-14 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=2000)),
                ('past_address', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('floor_count', models.PositiveIntegerField(default=0)),
                ('unit_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('owner', 'Owner'), ('resident', 'Resident'), ('staff', 'Staff')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='buildings.building')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'building', 'role'), name='unique_user_building_role')],
            },
        ),
    ]
