# Generated by Django 6.1.1 on 2026-09-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_floor_unit_tenany_ownership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='number',
            field=models.IntegerField(),
        ),
    ]
