# Generated by Django 6.1.1 on 2026-09-14 08:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_alter_unit_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tenany',
            new_name='Tenancy',
        ),
        migrations.AlterModelOptions(
            name='ownership',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='tenancy',
            options={'ordering': ['-start_date']},
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='star_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='tenancy',
            old_name='star_date',
            new_name='start_date',
        ),
    ]
