# Generated by Django 6.1.1 on 2026-09-14 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_rename_tenany_tenancy_alter_ownership_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unit',
            name='unique_floor_per_floor',
        ),
        migrations.RenameField(
            model_name='floor',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tenancy',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='buildingmembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='ownership',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('unit',), name='unique_active_ownership_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('unit',), name='unique_active_tenancy_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('floor', 'number'), name='unique_unit_per_floor'),
        ),
    ]
