# Generated by Django 6.1.1 on 2026-09-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_remove_unit_unique_floor_per_floor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='past_address',
        ),
        migrations.AddField(
            model_name='unit',
            name='past_address',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
