# Generated by Django 6.1.1 on 2026-09-16 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_remove_building_past_address_unit_past_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
