# Generated by Django 6.1.1 on 2026-09-21 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_building_created_at_building_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='floor',
            name='unique_floor_per_building',
        ),
        migrations.AlterField(
            model_name='unit',
            name='floor',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveConstraint(
            model_name='unit',
            name='unique_unit_per_floor',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='past_address',
            new_name='postal_code',
        ),
        migrations.AddField(
            model_name='building',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('office', 'Office'), ('industrial', 'Industrial')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='complex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='buildings.building'),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='parking_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='storage_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingmembership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('complex', 'number'), name='unique_unit_per_complex'),
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
    ]
