# Generated by Django 6.1.1 on 2026-09-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_remove_floor_unique_floor_per_building_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unit',
            name='unique_unit_per_complex',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='complex',
            new_name='building',
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('building', 'number'), name='unique_unit_per_complex'),
        ),
    ]
