# Generated by Django 6.1.1 on 2026-09-22 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_remove_unit_unique_unit_per_complex_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Floors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_count', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='unit',
            name='unique_unit_per_complex',
        ),
        migrations.RemoveField(
            model_name='building',
            name='floor_count',
        ),
        migrations.AddField(
            model_name='unit',
            name='ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_ownership', to='buildings.ownership'),
        ),
        migrations.AddField(
            model_name='unit',
            name='tenancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_tenancy', to='buildings.tenancy'),
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='unit_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingmembership',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='buildings.building'),
        ),
        migrations.AlterField(
            model_name='buildingmembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingmembership',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('owner', 'Owner'), ('resident', 'Resident'), ('staff', 'Staff')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='buildings.unit'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='buildings.unit'),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unit',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='parking_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='floors',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_floor', to='buildings.floors'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('building', 'floor'), name='unique_unit_per_floor'),
        ),
        migrations.RemoveField(
            model_name='unit',
            name='number',
        ),
    ]
