# Generated by Django 6.1.1 on 2026-09-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_floors_remove_unit_unique_unit_per_complex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='tenancy',
        ),
    ]
