# Generated by Django 6.1.1 on 2026-09-22 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0011_remove_unit_tenancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('pool', 'Pool'), ('function_hall', 'Function Hall'), ('roof_garden', 'Roof Garden')], max_length=30)),
                ('capacity', models.IntegerField(max_length=400)),
                ('hourly_rate', models.FloatField(max_length=4)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
            ],
        ),
        migrations.CreateModel(
            name='Facility_Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('fee_amount', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('canceled', 'Cancelled'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('pending', 'Pending')], max_length=30)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.facilities')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.unit')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resoled', 'Resolved'), ('closed', 'Closed')])),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')])),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.unit')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.tickets')),
            ],
        ),
    ]
