# Generated by Django 6.1.1 on 2026-09-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0012_announcements_facilities_facility_bookings_tickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='hourly_rate',
            field=models.FloatField(),
        ),
    ]
