# Generated by Django 6.1.1 on 2026-09-22 12:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0013_alter_facilities_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facility_Bookings',
            new_name='FacilityBookings',
        ),
    ]
