# Generated by Django 6.1.1 on 2026-09-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0014_rename_facility_bookings_facilitybookings'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unit',
            name='unique_unit_per_floor',
        ),
        migrations.AddField(
            model_name='unit',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('building', 'floor', 'number'), name='unique_unit_per_floor'),
        ),
    ]
