# Generated by Django 6.1.1 on 2026-09-27 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0015_remove_unit_unique_unit_per_floor_unit_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='tenancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_tenancy', to='buildings.tenancy'),
        ),
    ]
